version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/guess-game-web"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "typescript"
      - dependency-name: "primeng"
      - dependency-name: "primeicons"
      - dependency-name: "ngx-markdown"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
