version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore JaCoCo updates until bug fixes in JMockit
      - dependency-name: "org.jacoco:jacoco-maven-plugin"
  - package-ecosystem: "npm"
    directory: "/guess-game-web"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "typescript"
      - dependency-name: "primeng"
      - dependency-name: "primeicons"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
