---
dist: xenial

sudo: required

language: java

jdk: openjdk11

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.m2

before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml

script:
  - mvn clean package 

deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master
