---
dist: xenial

sudo: required

language: java

jdk: openjdk8

addons:
  chrome: stable

cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean package 

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
